name: gen-actions
on: [push]
jobs:
  gen-actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-24.11
    - run: make ymls
    - run: |
        git add .
        git config --global user.name xieby1-gen-actions
        git config --global user.email "miao@wang.zhi"
        git commit -m "gen actions $(git rev-parse HEAD)"
        git checkout actions
        git merge HEAD@{1} -X theirs -m "merge $(git rev-parse HEAD@{1})"
        git push
