name: gen-actions
on:
  push:
    branches:
      - main
jobs:
  gen-actions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # https://github.com/orgs/community/discussions/35410?sort=top
          # TLDR:
          # 1. Generate a Fine-grained token in https://github.com/settings/tokens
          #   1.1 Choose "All repositories" or "Only select repositories"
          #   1.2 Check contents:write, workflows:write
          # 2. Add the generated token to repository's action
          #   2.1 Repo > Settings > Secrets and variables > Actions
          #   2.2 In repository secrets, add a secret named WORKFLOW_TOKEN
          # The added secret will be used here
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - run: make ymls
      - name: make change to workflow file
        run: |
          git add .
          git config --global user.name xieby1-gen-actions
          git config --global user.email "miao@wang.zhi"
          git commit -m "gen actions $(git rev-parse HEAD)"
          git checkout actions
          git merge HEAD@{1} -X theirs -m "merge $(git rev-parse HEAD@{1})"
          git push
