name: gen-actions
on: [push]
jobs:
  gen-actions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        # https://github.com/orgs/community/discussions/35410#discussioncomment-7645702
        # Fine-grained PAT with contents:write and workflows:write
        # scopes
        token: ${{ secrets.WORKFLOW_TOKEN }}
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-24.11
    - run: make ymls
    - name: Make change to workflow file
      run: |
        git add .
        git config --global user.name xieby1-gen-actions
        git config --global user.email "miao@wang.zhi"
        git commit -m "gen actions $(git rev-parse HEAD)"
        git checkout actions
        git merge HEAD@{1} -X theirs -m "merge $(git rev-parse HEAD@{1})"
        git push
