jobs:
  tldr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-24.05
    - run: nix-build ./mypkgs.nix -A tldr
name: tldr
'on':
  push:
    branches:
    - actions
